# See config.example.yml for documentation.
object: orig/DOLSDK-2001-05-22/sys/main.dol
hash: 0123456789abcdef0123456789abcdef01234567
symbols: config/DOLSDK-2001-05-22/symbols.txt
splits: config/DOLSDK-2001-05-22/splits.txt
mw_comment_version: 8

modules:
- object: orig/DOLSDK-2001-05-22/files/os.a
  hash: 0123456789abcdef0123456789abcdef01234567
  symbols: config/DOLSDK-2001-05-22/os/symbols.txt
  splits: config/DOLSDK-2001-05-22/os/splits.txt
